### ISSUE TITLE
fetchPools() issue with Polygon Mainnet

### ISSUE THREAD

**Issue by michaelr524** [balancer/balancer-sor#395]
Hi,

Ethereum works great, but Polygon gives the following error when calling fetchPools(). 
Does anyone know how to make it work with Polygon as well?

> 2023-07-10 02:16:21 calling swaps.fetchPools()
2023-07-10 02:16:21 137 fetching pools...
Error: fetchPools(): Error: Issue with pool onchain data: Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)

**Comment by brunoguerios** [comment]
Hey there 👋 
Thanks for the feedback.
I'll take a look and get back to you as soon as I have an update.

**Comment by michaelr524** [comment]
Hey Bruno! 

Thanks for the quick reply!

- using the latest version of the sdk 1.1.2
- here is a small reproducible example: https://github.com/michaelr524/sor-reproduce/tree/main

**Comment by brunoguerios** [comment]
Hey Michael 👋 
I believe we have a fix for what you're experiencing on the `beta` release.
I updated it in your example and the error no longer happened.
I must say I had to update the rpcUrl to another one to get the example going, but I think it's an unrelated issue.
Are you ok on using `beta` for a couple of weeks until we're able to release a new `latest` version?

**Comment by michaelr524** [comment]
Updated to the latest beta and it works perfectly at the moment. Thank you for your help!

A question regarding fetchPools() if I may. Is the best strategy for quick quotes to run fetchPools() in a loop in a background timer/thread?

**Comment by brunoguerios** [comment]
I believe so 👍 
Although our [frontend](https://github.com/balancer/frontend-v2/blob/12caddcb24b337697916e20e8f0bb5bf8f129d2c/src/services/balancer/pools/joins/handlers/swap-join.handler.ts#L64) currently doesn't seem to be using it that way. They fetch the first time it's required and persist that amount. I'm not sure about how/when they refresh the data, but I'd say that's quite specific to how you expect your solution to work.
Feel free to take a deeper look into how it's done there and see if it makes sense for your scenario.

**Comment by michaelr524** [comment]
Thanks
