### ISSUE TITLE
Swap Limit Error

### ISSUE THREAD

**Issue by brunoguerios** [balancer/balancer-sor#424]
Instead of throwing an error "Swap amount exceeds the pool limit" - exclude the pool from the pool from the path building. (and maybe log an error, so we know about it with a poolId)

**Comment by brunoguerios** [comment]
@gmbronco - since you created this issue, could you please provide more details on how to reproduce?

**Comment by gmbronco** [comment]
fixed in https://github.com/balancer/b-sdk/pull/158
