### ISSUE TITLE
Add config for Base

### ISSUE THREAD

**Issue by brunoguerios** [balancer/balancer-sor#425]

**Comment by brunoguerios** [comment]
@gmbronco - since you created the task, could you please add a bit more info? Maybe a template or an example of another chain config?

**Comment by gmbronco** [comment]
i'll take care of it. here is the config from recent fanom PR: https://github.com/balancer/b-sdk/pull/102/files

**Comment by brunoguerios** [comment]
This issue was created in the wrong repo - I'll close as it's already being handled elsewhere.
